[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_vault_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
vault_relayer = "4iT8Sw1YvbmtRR8qj8ZDwf8J74rxRUTGVHn9vLNHk6FF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
